Repository seantomburke/sitemapper, pull requests merged in 2022-07, with the labels that each got.

#101 fix #98: fix rejectUnauthorized option value
  src/assets/sitemapper.js
Labels: size/XS

#107 [public-square:master] Add ability to filter urls by lastmod
  README.md
  lib/assets/sitemapper.js
  package-lock.json
  sitemapper.d.ts
  src/assets/sitemapper.js
  src/tests/test.js
Labels: size/L

#108 Improving debug
  src/assets/sitemapper.js
Labels: size/XS

#109 Improve debug
  lib/assets/sitemapper.js
Labels: size/XS

#110 Adding Badges
  README.md
Labels: size/S
