Repository seantomburke/sitemapper, pull requests merged in 2024-11, with the labels that each got.

#155 Resolves issue #154: Enables field parsing even when some items may not include field
  src/assets/sitemapper.js
  src/tests/test.ts.ts
Labels: size/XS

#156 Update Packages
  .eslintrc.js
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
  .github/workflows/version-bump.yml
  .prettierignore
  .prettierrc.js
  .travis.yml
  CONTRIBUTING.md
  README.md
  babel.config.js
  cspell.json
  docs.md
  eslint.config.mjs
  example.es6.js
  example.js
  package-lock.json
  package.json
  sitemapper.d.ts
  src/assets/sitemapper.js
  src/examples/google.js
  src/tests/test.es5.js
  src/tests/test.js
  src/tests/test.ts.ts
  src/tests/tsconfig.json
Labels: size/XXL

#157 Converting to using fast-xml-parser
  package-lock.json
  package.json
  src/assets/sitemapper.js
  src/examples/index.js
Labels: size/M
