Repository seantomburke/sitemapper, pull requests merged in 2025-05, with the labels that each got.

#164 Support sitemaps with namespace prefix
  src/assets/sitemapper.js
  src/tests/test.ts.ts
Labels: size/S

#166 Add CLI support and bump minor version
  bin/sitemapper.js
  package-lock.json
  package.json
  src/tests/cli.test.js
  src/tests/test.ts.ts
Labels: size/M

#167 Syntax Error
  src/tests/cli.test.js
Labels: size/XS

#161 Added option to return sub-sitemap URLs in results
  README.md
  package-lock.json
  package.json
  sitemapper.d.ts
  src/assets/sitemapper.js
  src/tests/type-check.ts
Labels: size/M

#168 Modernize codebase with ES modules and TypeScript
  .github/workflows/npm-publish.yml
  .github/workflows/test.yml
  .github/workflows/typescript-test.yml
  .prettierrc.js
  README.md
  babel.config.js
  bin/sitemapper.js
  eslint.config.js
  package-lock.json
  package.json
  src/tests/cli.test.ts
  src/tests/test.ts.ts
  src/tests/tsconfig.json
Labels: size/M

#170 Update dependencies to latest versions
  eslint.config.js
  package-lock.json
  package.json
Labels: size/M

#172 Update Node.js requirement from 10+ to 18+
  package.json
Labels: size/XS

#173 Fix publish action
  .github/workflows/npm-publish.yml
  README.md
  eslint.config.js
Labels: size/S

#174 Optimize GitHub Actions Workflow and Add Spell Checking
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
  .github/workflows/typescript-test.yml
  .github/workflows/version-bump.yml
  README.md
  cspell.json
  package-lock.json
  package.json
  src/assets/sitemapper.js
  src/examples/google.js
  src/tests/type-check.ts
Labels: size/L

#175 Retry Tests
  .github/workflows/test.yml
Labels: size/XS

#176 📚 Modernize and improve README.md
  README.md
Labels: size/L

#179 Add code coverage improvements
  .claude/settings.local.json
  src/tests/additional-coverage.test.ts
  src/tests/increase-coverage.test.ts
Labels: size/XXL
